site_name: Лабораторная работа №2 — Потоки. Процессы. Асинхронность
site_description: Документация по лабораторной работе №2 (Threading, Multiprocessing, Async)
site_author: Владзиевский Евгений (K3341)
repo_url: https://github.com/lk2322/ITMO_ICT_WebDevelopment_tools_2025-2026
repo_name: GitHub
docs_dir: docs

theme:
  name: material
  language: ru
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Главная: index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - tables
  - admonition
